"""version 1.0

Revision ID: 545c3ce12df3
Revises: e7f8a9b0c1d2
Create Date: 2026-04-10 00:52:36.982865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '545c3ce12df3'
down_revision: Union[str, Sequence[str], None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'role',
               existing_type=postgresql.ENUM('admin', 'host', 'super_admin', name='staff_role'),
               server_default='admin',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'role',
               existing_type=postgresql.ENUM('admin', 'host', 'super_admin', name='staff_role'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
