"""lol fixed

Revision ID: 6470431ea85e
Revises: 95ac9db051dc
Create Date: 2026-04-09 14:58:03.160118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6470431ea85e'
down_revision: Union[str, Sequence[str], None] = '95ac9db051dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_checks', 'lol',
               existing_type=sa.VARCHAR(length=32),
               server_default='NIGGERS',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_checks', 'lol',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
