"""...

Revision ID: 95ac9db051dc
Revises: 0002_add_system_checks_table
Create Date: 2026-04-09 14:54:40.960729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ac9db051dc'
down_revision: Union[str, Sequence[str], None] = '0002_add_system_checks_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_checks', sa.Column('lol', sa.String(length=32), nullable=True))
    op.alter_column('system_checks', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('system_checks', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_checks', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('system_checks', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('system_checks', 'lol')
    # ### end Alembic commands ###
