"""PIZDA

Revision ID: d419cb9890c1
Revises: 9a0fa42a4c8d
Create Date: 2026-04-09 22:05:30.877347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd419cb9890c1'
down_revision: Union[str, Sequence[str], None] = '9a0fa42a4c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Enum('default', 'tournament', name='event_type'), server_default='default', nullable=False),
    sa.Column('price_per_game', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('nick', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=128), nullable=True),
    sa.Column('social_link', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('nick', name=op.f('uq_players_nick'))
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables'))
    )
    op.create_table('event_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paid_amount', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_player_event_id_events')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_event_player_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_player'))
    )
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('preparation', 'active', 'finished', name='game_status'), server_default='preparation', nullable=False),
    sa.Column('result', sa.Enum('civilian', 'mafia', 'ppk_civilian', 'ppk_mafia', 'continues', name='game_result'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_games_event_id_events')),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name=op.f('fk_games_table_id_tables')),
    sa.PrimaryKeyConstraint('game_id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_event_id'), 'games', ['event_id'], unique=False)
    op.create_index(op.f('ix_games_table_id'), 'games', ['table_id'], unique=False)
    op.create_table('game_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('fouls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extra_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('role', sa.Enum('civilian', 'sheriff', 'mafia', 'don', name='participant_role'), nullable=False),
    sa.Column('is_alive', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name=op.f('fk_game_participants_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_game_participants_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_participants'))
    )
    op.create_index(op.f('ix_game_participants_game_id'), 'game_participants', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_participants_player_id'), 'game_participants', ['player_id'], unique=False)
    op.create_table('game_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name=op.f('fk_game_player_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_game_player_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_player'))
    )
    op.create_table('shooting_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('shooter_player_id', sa.Integer(), nullable=False),
    sa.Column('target_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name=op.f('fk_shooting_rounds_game_id_games')),
    sa.ForeignKeyConstraint(['shooter_player_id'], ['players.id'], name=op.f('fk_shooting_rounds_shooter_player_id_players')),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.id'], name=op.f('fk_shooting_rounds_target_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shooting_rounds'))
    )
    op.create_index(op.f('ix_shooting_rounds_game_id'), 'shooting_rounds', ['game_id'], unique=False)
    op.create_index(op.f('ix_shooting_rounds_shooter_player_id'), 'shooting_rounds', ['shooter_player_id'], unique=False)
    op.create_index(op.f('ix_shooting_rounds_target_player_id'), 'shooting_rounds', ['target_player_id'], unique=False)
    op.create_table('testaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name=op.f('fk_testaments_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_testaments_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testaments')),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_testaments_game_id_player_id')
    )
    op.create_index(op.f('ix_testaments_game_id'), 'testaments', ['game_id'], unique=False)
    op.create_index(op.f('ix_testaments_player_id'), 'testaments', ['player_id'], unique=False)
    op.create_table('voting_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('is_tie', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name=op.f('fk_voting_rounds_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_rounds')),
    sa.UniqueConstraint('game_id', 'round_number', name='uq_voting_rounds_game_id_round_number')
    )
    op.create_index(op.f('ix_voting_rounds_game_id'), 'voting_rounds', ['game_id'], unique=False)
    op.create_table('testament_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testament_id', sa.Integer(), nullable=False),
    sa.Column('target_player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.id'], name=op.f('fk_testament_targets_target_player_id_players')),
    sa.ForeignKeyConstraint(['testament_id'], ['testaments.id'], name=op.f('fk_testament_targets_testament_id_testaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testament_targets')),
    sa.UniqueConstraint('testament_id', 'position', name='uq_testament_targets_testament_id_position')
    )
    op.create_index(op.f('ix_testament_targets_target_player_id'), 'testament_targets', ['target_player_id'], unique=False)
    op.create_index(op.f('ix_testament_targets_testament_id'), 'testament_targets', ['testament_id'], unique=False)
    op.create_table('voting_nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_round_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_voting_nominations_player_id_players')),
    sa.ForeignKeyConstraint(['voting_round_id'], ['voting_rounds.id'], name=op.f('fk_voting_nominations_voting_round_id_voting_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_nominations')),
    sa.UniqueConstraint('voting_round_id', 'player_id', name='uq_voting_nominations_round_player')
    )
    op.create_index(op.f('ix_voting_nominations_player_id'), 'voting_nominations', ['player_id'], unique=False)
    op.create_index(op.f('ix_voting_nominations_voting_round_id'), 'voting_nominations', ['voting_round_id'], unique=False)
    op.create_table('voting_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_round_id', sa.Integer(), nullable=False),
    sa.Column('voter_player_id', sa.Integer(), nullable=False),
    sa.Column('target_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.id'], name=op.f('fk_voting_votes_target_player_id_players')),
    sa.ForeignKeyConstraint(['voter_player_id'], ['players.id'], name=op.f('fk_voting_votes_voter_player_id_players')),
    sa.ForeignKeyConstraint(['voting_round_id'], ['voting_rounds.id'], name=op.f('fk_voting_votes_voting_round_id_voting_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_votes')),
    sa.UniqueConstraint('voting_round_id', 'voter_player_id', name='uq_voting_votes_round_voter')
    )
    op.create_index(op.f('ix_voting_votes_target_player_id'), 'voting_votes', ['target_player_id'], unique=False)
    op.create_index(op.f('ix_voting_votes_voter_player_id'), 'voting_votes', ['voter_player_id'], unique=False)
    op.create_index(op.f('ix_voting_votes_voting_round_id'), 'voting_votes', ['voting_round_id'], unique=False)
    op.alter_column('admins', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('system_checks', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('system_checks', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_checks', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('system_checks', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('admins', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_voting_votes_voting_round_id'), table_name='voting_votes')
    op.drop_index(op.f('ix_voting_votes_voter_player_id'), table_name='voting_votes')
    op.drop_index(op.f('ix_voting_votes_target_player_id'), table_name='voting_votes')
    op.drop_table('voting_votes')
    op.drop_index(op.f('ix_voting_nominations_voting_round_id'), table_name='voting_nominations')
    op.drop_index(op.f('ix_voting_nominations_player_id'), table_name='voting_nominations')
    op.drop_table('voting_nominations')
    op.drop_index(op.f('ix_testament_targets_testament_id'), table_name='testament_targets')
    op.drop_index(op.f('ix_testament_targets_target_player_id'), table_name='testament_targets')
    op.drop_table('testament_targets')
    op.drop_index(op.f('ix_voting_rounds_game_id'), table_name='voting_rounds')
    op.drop_table('voting_rounds')
    op.drop_index(op.f('ix_testaments_player_id'), table_name='testaments')
    op.drop_index(op.f('ix_testaments_game_id'), table_name='testaments')
    op.drop_table('testaments')
    op.drop_index(op.f('ix_shooting_rounds_target_player_id'), table_name='shooting_rounds')
    op.drop_index(op.f('ix_shooting_rounds_shooter_player_id'), table_name='shooting_rounds')
    op.drop_index(op.f('ix_shooting_rounds_game_id'), table_name='shooting_rounds')
    op.drop_table('shooting_rounds')
    op.drop_table('game_player')
    op.drop_index(op.f('ix_game_participants_player_id'), table_name='game_participants')
    op.drop_index(op.f('ix_game_participants_game_id'), table_name='game_participants')
    op.drop_table('game_participants')
    op.drop_index(op.f('ix_games_table_id'), table_name='games')
    op.drop_index(op.f('ix_games_event_id'), table_name='games')
    op.drop_table('games')
    op.drop_table('event_player')
    op.drop_table('tables')
    op.drop_table('players')
    op.drop_table('events')
    # ### end Alembic commands ###
